name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build_and_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: SetupGolang
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Print Go Version
        run : go version

      - name: Get Dependencies
        run : go mod download

      - name : Go Build
        run: go build -v .

  deployment :
    needs : build_and_tests
    runs-on: ubuntu-latest
    if : github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Dependencies
        run : go mod download

      - name: SetupGolang
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Go Build
        run: go build -o TestApp

      - name: Deploy
        uses: appleboy/ssh-action@v3.3.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            pkill -f TestApp || true
            cp /tmp/TestApp ~/TestApp
            chmod +x ~/myapp
            nohup ~/myapp > ~/app.log 2>&1 &
          scp: TestApp:/tmp/TestApp